version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - justinebateman
  ignore:
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
    - 4.6.0
  - dependency-name: webpack
    versions:
    - 4.46.0
    - 5.36.1
  - dependency-name: babel-loader
    versions:
    - 8.1.0
    - 8.2.2
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: swagger-ui-dist
    versions:
    - 3.41.1
    - 3.42.0
    - 3.43.0
    - 3.44.0
    - 3.44.1
    - 3.45.0
    - 3.45.1
    - 3.46.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
    - 6.5.4
  - dependency-name: webpack-dev-server
    versions:
    - 3.11.2
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: react-dom
    versions:
    - 16.13.1
